name: Github actions - Push template basic
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
        - main

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
       - name: Comentário
         run: |
           echo "Comentário do workflow push"